### ISSUE TITLE
mobile-wallet-adapter plugin for web app even doesn't work on your demo

### ISSUE THREAD

**Issue by Mahdiyar2006** [solana-mobile/mobile-wallet-adapter#115]
mobile-wallet-adapter plugin for web app doesn't work and it is not working even in your demo
demo: https://solana-labs.github.io/wallet-adapter/example/

**Comment by sdlaver** [comment]
Hi @Mahdiyar2006, sorry to hear that you're encountering issues. While we have observed the demo working in our testing, we're happy to help investigate any failure(s) you are encountering. Would you be able to post the JS console output, plus the device or emulator logcat, and we'll take a look?

**Comment by sdlaver** [comment]
No response in > 7 days. Closing; please re-open if you have error logs to share.
