### ISSUE TITLE
add skip_preflight and cluster option in mobile-wallet-adapter-protocol-web3js

### ISSUE THREAD

**Issue by banditesq** [solana-mobile/mobile-wallet-adapter#130]
Add skip_preflight (default true) and cluster option in mobile-wallet-adapter-protocol-web3js package ( sign_and_send_transaction) method.

**Comment by sdlaver** [comment]
Hi @banditesq, as part of PR #111, we're discussing the future of these two parameters.

- `cluster` will move to the `authorize` method, and apply at the authorization level. We can use this issue to track adding the parameter to the `authorize` method in `mobile-wallet-adapter-protocol-web3js`
- `skip_preflight` will be removed from the API surface. dApps that want to skip preflight can do so by utilizing `sign_transaction` and sending it themselves, with appropriate options, to a RPC node.
