### ISSUE TITLE
Add a clientlib API to detect if there are any MWA-supporting wallets present

### ISSUE THREAD

**Issue by sdlaver** [solana-mobile/mobile-wallet-adapter#152]

**Comment by steveluscher** [comment]
Yes please! When this is done I can add a property / listener to the React Native API to let an app know whether there are any wallets or none.

Can you also, as part of this, let me _subscribe_ to that state? I want to know when the wallet-havingness of a phone changes (eg. I want my app to receive an event when the user installs their first wallet).
