### ISSUE TITLE
Accounts should have human-readable labels

### ISSUE THREAD

**Issue by steveluscher** [solana-mobile/mobile-wallet-adapter#187]
Using a dApp today demands that you memorize part of a base58 encoded public key, because that's the primary way by which a given account in your wallet is represented.

In the wallets on the other hand, you're allowed to add convenient, human-readable labels, like ‘My NFT wallet.’

Mobile wallet adapter must allow the flow of account labels to dapp endpoints who can then use them to enhance the user experience by showing human-readable labels alongside the addresses to which they pertain.

# Summary of changes

- [X] Update the spec to return `{address: Base64EncodedAddress, label?: string}` from `authorize` and `reauthorize`. dApps can now use that label in their UI for a better experience.
  #184
- [x] Update JavaScript protocol method signatures
  #184
- [x] Update React Native Example App to display labels
  #184
- [x] Update Web example app to handle accounts with labels
  #184
- [x] Update server/client implementation to supply labels with accounts
  #184    
- [ ] Update KTX example app to display labels

**Comment by steveluscher** [comment]
@creativedrewy, want to bring the KTX example app home? See #184 for screenshot of the changes to the React Native example.

**Comment by creativedrewy** [comment]
Oooh, I love it! I will do that for sure.
