### ISSUE TITLE
[spec feedback] Accounts should be base58 encoded

### ISSUE THREAD

**Issue by vpontis** [solana-mobile/mobile-wallet-adapter#208]
<img width="763" alt="CleanShot 2022-08-06 at 23 25 59@2x" src="https://user-images.githubusercontent.com/1319079/183273714-290a4fe5-48db-4ae5-9a0b-f5a37a58b783.png">

This will be a common bug. I think accounts should always be base58 encoded.

**Comment by steveluscher** [comment]
This is the way we had it originally. https://github.com/solana-mobile/mobile-wallet-adapter/issues/142

It’s our opinion that base58 encoding is a presentation layer concern and not a protocol level concern. https://github.com/solana-mobile/mobile-wallet-adapter/pull/111

In defense of that position, I’ll note that Ethereum addresses present in base16. Hence we’d like to maintain a distinction between the wire format of an address at the MWA protocol layer, and the multiple ways a UI might like to format those addresses, which we’ll leave up to higher-level frameworks and/or dapps.

**Comment by vpontis** [comment]
Gotcha, I understand your reasoning. But I still think that a lot of developers are going to run into issues with this haha :)
