### ISSUE TITLE
[spec feedback] Auth token guidance

### ISSUE THREAD

**Issue by vpontis** [solana-mobile/mobile-wallet-adapter#209]
From my understanding, the connection protocol works as so:

1. the dApp makes a request to the wallet — "hey I want to connect to you
2. the wallet asks the user if she wants to connect
3. if she's ok with it, the wallet creates an random auth token and sends it back to the dApp
4. the dApp can now use this token to make subsequent requests

Is this flow correct?

If so, how should the wallet app store auth tokens? How should they be generated / how long should they last?

**Comment by creativedrewy** [comment]
I can comment on storing the auth token. As I understand it, it would be totally okay to store the auth token even in something like shared preferences since it's just an "operation" token and not the user's private key/seed phrase.

**Comment by sdlaver** [comment]
That flow is spot on. A few comments:

> the wallet creates an random auth token

It doesn't have to be random - it can have meaning, if the wallet so chooses. From the dapps perspective, it is merely a unique and secret value representing the particular authorization issued by a wallet to a dapp.

> How should they be generated / how long should they last?

walletlib has a stock implementaton of auth token issuance. The sample implementation offers two different levels of validity:

1. For first 1 hour, the auth token is a bearer token. When presented, it is treated as proof of identity, and allows session reauthorization to proceed immediately.
2. For the next 3 weeks, it is no longer valid, but still renewable. The exact meaning of renewal is wallet-specific, but the intent is that wallets will perform lesser checks (perhaps re-running dapp identity verification, but not actively re-requesting user authorization of the dapp).
3. After 3 weeks, it has expired. It is not renewable - the dapp will need to `authorize` again from scratch.

> how should the wallet app store auth tokens?

The walletlib reference implementation stores up to 50 auth tokens for each dapp in a SQLite database.
