### ISSUE TITLE
[spec feedback] Sign messages interface

### ISSUE THREAD

**Issue by vpontis** [solana-mobile/mobile-wallet-adapter#211]
This is the current proposal.

```
{
    "addresses": ["<address>", ...],
    “payloads”: [“<message>”, ...],
}
```

I found this very confusing and after reading the docs, I was still confusing. 

If there are 2 messages and 3 addresses, does that mean there are 6 signatures? If so, what order are they in?

---

Instead, I think you can do:

```
// request
Array<{ address: string; message: string; }>

// response
Array<{ address: string; message: string; signature: string }>
```

**Comment by steveluscher** [comment]
I thought this was confusing too. The answer is that you will receive back one signed payload for each payload supplied.

How that single signed message will incorporate multiple signers is an open topic, tracked here: https://github.com/solana-mobile/mobile-wallet-adapter/issues/193
