### ISSUE TITLE
sign and send transaction error

### ISSUE THREAD

**Issue by mohanbright** [solana-mobile/mobile-wallet-adapter#242]
While signing and sending transaction in publish memo if Memo Program is changed to System Program to send transaction it's throwing error of JsonRpc20RemoteException: -2/payloads invalid for signing, can anyone please help how to sign and send transactions from one account to another

**Comment by sdlaver** [comment]
Hi @mohanbright, would you mind coming to the #sdk channel in the Solana Mobile Discord to discuss this issue?
https://discord.gg/solanamobile
