### ISSUE TITLE
yarn install error

### ISSUE THREAD

**Issue by faisalKhan-99** [solana-mobile/mobile-wallet-adapter#309]
Getting this upon running "yarn install" in example react native app and as a result node_modules folder is not generating
![image](https://user-images.githubusercontent.com/78919021/196642140-e15522fa-aebc-48cd-85f2-104456ec8e6b.png)

**Comment by faisalKhan-99** [comment]
was able to get past this by removing yarn build from package.json, now the line looks like " "preinstall": "rm -rf node_modules/ && (cd ../../js/ && yarn )""
stuck at 
![image](https://user-images.githubusercontent.com/78919021/196665452-5f4e0492-74a8-4038-955d-fec3454913f6.png)

**Comment by steveluscher** [comment]
The long and the short of it, is that we don't support building on Windows. Install [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install)!
