### ISSUE TITLE
`fakedapp` should be able to create versioned transactions (for testing purposes)

### ISSUE THREAD

**Issue by sdlaver** [solana-mobile/mobile-wallet-adapter#344]
1. Add a dropdown to `fakedapp` to allow selecting transaction format to create (legacy or v0)
2. Rename existing `MemoTransactionuseCase` class to `MemoTransactionLegacyUseCase`
3. Extract an interface from `MemoTransactionLegacyUseCase`
4. Implement `MemoTransactionV0UseCase`
5. Validate with existing MWA wallets (e.g. Phantom, Solflare) that support V0 transactions (see the output of the `get_capabilities` MWA request to verify) and with `fakewallet` on Saga and on Android simulator (to check both in-wallet signing and Seed Vault signing)

**Comment by Funkatronics** [comment]
I have the V0 message format working, tested so far with both phantom and the fake wallet (with some added support for signing V0 txns). Just need to button everything up and attach stuff to the UI.

**Comment by Funkatronics** [comment]
fixed in #346
