### ISSUE TITLE
Cleanup Authorize/Reauthorize API

### ISSUE THREAD

**Issue by Funkatronics** [solana-mobile/mobile-wallet-adapter#436]
## Summary
The current mobile wallet adapter API defines both an `authorize` call and a `reauthorize` call. It is unclear how to correctly use these methods in an application (based on developer feedback). The authorization API will be updated to combine these two methods into a single API. 

### Tasks
- [x] https://github.com/solana-mobile/mobile-wallet-adapter/issues/437
- [x] Implement Authorization API in Mobile Wallet Adapter
- [x] Update Documentation

**Comment by Funkatronics** [comment]
related issue: https://github.com/solana-mobile/mobile-wallet-adapter/issues/369

this new API should account for this, and make the suggested improvements to clientlib-ktx

**Comment by yveskalume** [comment]
Hello @Funkatronics Can I work on this ?

**Comment by Funkatronics** [comment]
Hey apologies for not seeing your comment here @yveskalume! we've been finalizing the MWA 2.0 spec [here](https://github.com/solana-mobile/mobile-wallet-adapter/pull/521) and this ticket has already been included.
