### ISSUE TITLE
Write a few notes about the limitations of web-based MWA in the context of browser popup blockers

### ISSUE THREAD

**Issue by steveluscher** [solana-mobile/mobile-wallet-adapter#442]
Convert this: https://discord.com/channels/988649555283308564/1100745937971859516/1101225927477821670

Into README content in https://github.com/solana-mobile/mobile-wallet-adapter/tree/main/js/packages

**Comment by Michaelsulistio** [comment]
https://github.com/solana-mobile/mobile-wallet-adapter/pull/448
