### ISSUE TITLE
React Native Wallet SDK v0.1

### ISSUE THREAD

**Issue by Funkatronics** [solana-mobile/mobile-wallet-adapter#459]
Initial Release of React Native Wallet SDK

Goals: v0.1 should be fully functional with a reasonably stable API. Further improvements and feature additions will be added as wallet partners intergrade the library and provide feedback. 

Tasks:

- [x] https://github.com/solana-mobile/mobile-wallet-adapter/pull/443
- [x] https://github.com/solana-mobile/mobile-wallet-adapter/issues/458
- [x] Request Correlation, Handle Multiple Requests
- [x] Session Establishment

**Comment by Michaelsulistio** [comment]
Do we want to close out that [WIP] branch as is and just merge it into main, like we discussed? Then the rest of the follow up tasks we can work in separate branches .

**Comment by Funkatronics** [comment]
yeah that would probably be best.

**Comment by Funkatronics** [comment]
done, Mike released a v0.1 release to npm
