### ISSUE TITLE
React Native Auto Connect

### ISSUE THREAD

**Issue by oktaysenkan** [solana-mobile/mobile-wallet-adapter#470]
Is this package supports auto connect for react native?

`@solana/wallet-adapter-react/WalletProvider` component does not work on react native.

```ts
await transact(async wallet => {
  wallet.reauthorize(oldToken)
});
```

`wallet.reauthorize` needs pin code to unlock, i want to direct auto connect without any prompt.

**Comment by sdlaver** [comment]
Hi @oktaysenkan, how a wallet handles the `authorize`/`reauthorize` methods is a detail that is left to the wallets themselves; the `mobile-wallet-adapter` project doesn't prescribe any particular UI for the wallets. Which wallet(s) are you observing this behavior with?

**Comment by oktaysenkan** [comment]
I am using Solflare.

https://github.com/open-sauce-labs/solomon/blob/e85dd073bac0f58d0cb5b37db42f2f41fc64ba2a/src/providers/MobileWalletProvider.tsx#L49
https://github.com/open-sauce-labs/solomon/blob/e85dd073bac0f58d0cb5b37db42f2f41fc64ba2a/src/providers/AuthProvider.tsx#L82

I did some research on GitHub and i found these.

**Comment by oktaysenkan** [comment]
```ts
const test = async () => {
  await transact(async wallet => {
    console.log(wallet);
  });
};
```

`transact` function needs verification every time. I think the only way to change it is in the wallet settings

![CleanShot 2023-05-22 at 19 50 58@2x](https://github.com/solana-mobile/mobile-wallet-adapter/assets/42527467/05104846-04d0-41a8-b610-94a4683b4216)
