### ISSUE TITLE
Fake wallet does not render SVG icons

### ISSUE THREAD

**Issue by steveluscher** [solana-mobile/mobile-wallet-adapter#56]
We should consider making the fake wallet app able to render any reasonable kind of `icon`, or should specify which image formats are allowed. Right now it doesn't appear to render SVG files.

**Comment by devacros** [comment]
I opened a PR regarding this 

https://github.com/solana-mobile/mobile-wallet-adapter/pull/73

Coil library will make it easier to support svg and regular images at the same time on the fakewallet app ( I guess at the end of the day the wallet developer can use any library)

Ideally the `AuthorizeRequest` can have a `getIdentifyType` method which lets the wallet know that it needs to display a svg, png, gif, etc.
