### ISSUE TITLE
[Need Help] Sign message is not working after connect wallet

### ISSUE THREAD

**Issue by fahimfaisaal** [solana-mobile/mobile-wallet-adapter#606]
Hello fellow programmers,

I'm currently utilizing the `SolanaMobileWalletAdapter` TypeScript class to establish a connection and sign messages in my mobile app. However, I'm encountering a hurdle in the sign message process. 

When I press the `Mobile Wallet Adapter` provider before connecting, it displays app options smoothly, and the wallet connects successfully. But after connecting the wallet, I attempt to sign a message to verify the wallet by triggering the `signMessage` function. 

Unfortunately, I face an issue. It shows the message: `Found no installed wallet that supports the mobile wallet protocol.` and redirects me to `https://solanamobile.com/wallets`.

**Comment by sdlaver** [comment]
cc/ @Michaelsulistio

**Comment by Michaelsulistio** [comment]
@fahimfaisaal Hey, let me try and diagnose the issue.

Couple of sanity questions:
1. Can you send a screenshot of your package.json? I want to verify the versions of the libraries you're using.
2. Can you send a code snippet of the connect code you're trying to call?
3. Is this a React Native or Expo app? Is it Android?

**Comment by Michaelsulistio** [comment]
On second read, this is likely the Android Chrome limitation when trying to `connect` + `signMessage` in a single user action. TLDR, chrome will block navigation that does not stem from a user action (e.g `signMessage` in a `useEffect`). 

See [this](https://github.com/solana-mobile/mobile-wallet-adapter/tree/main/js/packages/wallet-adapter-mobile#android-chrome-browser-issues) and [Chrome Android Intent docs](https://developer.chrome.com/docs/android/intents) for more information on why this is a Chrome limitation.

A quick solution here is to split the sign in flow into two user clicks, `connect` click and `signMessage` click.
