### ISSUE TITLE
Solaner

### ISSUE THREAD

**Issue by SunSchizzzz** [solana-mobile/mobile-wallet-adapter#625]
**Describe the bug**

**To Reproduce**
1. Install app '...'
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Saga, Pixel 7, etc.]
 - Browser: if this issue is related to mobile web [e.g. Chrome, Firefox]
 - Version: if this issue is endemic to specific Android versions [e.g. 22]
 - Additonal Details: any additonal information about the device? [e.g. low power mode on, privacy mode on, etc.]

**Additional context**

**Comment by sdlaver** [comment]
Closing empty issue report
