### ISSUE TITLE
how to open detail page of dapp in solana dapp store by deep link?

### ISSUE THREAD

**Issue by kukufree** [solana-mobile/mobile-wallet-adapter#648]
like deep link in google play store:
https://play.google.com/store/apps/details?id=io.metamask

**Comment by kukufree** [comment]
is like this?
https://store.solanamobile.com/apps/details?id=io.metamask

**Comment by sdlaver** [comment]
@ankur2136 would you mind handling this one?

**Comment by ankur2136** [comment]
Hi @kukufree 
you can trigger deeplinks to dapp store details page with following
```
    android:host="details"
    android:scheme="solanadappstore"
```

Sample terminal command

```
adb shell am start -a android.intent.action.VIEW -d  "solanadappstore://details?id=com.solanamobile.mintyfresh"
``` 

where `com.solanamobile.mintyfresh` is the name of the package 

Sample android code

```
    val intent = Intent(Intent.ACTION_VIEW)
    intent.data = "solanadappstore://details?id=com.solanamobile.mintyfresh".toUri()
    context.startActivity(intent)
```

**Comment by kukufree** [comment]
@ankur2136 Thanks a lot!
