### ISSUE TITLE
spec page css is wrong, style is break

### ISSUE THREAD

**Issue by katopz** [solana-mobile/mobile-wallet-adapter#72]
refer to: https://solana-mobile.github.io/mobile-wallet-adapter/spec/spec.html
current hit `404` at `https://solana-mobile.github.io/assets/css/just-the-docs-default.css`

because
```html
<link rel="stylesheet" href="/assets/css/just-the-docs-default.css">
```

expected `https://solana-mobile.github.io/mobile-wallet-adapter/spec/assets/css/just-the-docs-default.css`

**Comment by sdlaver** [comment]
Thank you! We missed this in the flurry of the announcement yesterday.
