### ISSUE TITLE
Please help me answer another question. Thank you very much.

### ISSUE THREAD

**Issue by huangli446688** [solana-mobile/mobile-wallet-adapter#82]
In the Android demo, when DAPP starts to authorize the connection, after pulling up the wallet application, it delays sending messages to the wallet for 100 milliseconds, and then the connection timeout is 20 milliseconds. I think the 100 millisecond delay is too short, and the 20 millisecond connection timeout is too short. Because many wallets are flutter applications, the time to start an application is far more than 100 milliseconds, and the connection timeout is 20 milliseconds, which is not enough for some applications and scenarios. This is the problem I encountered when accessing your SDK.

**Comment by sdlaver** [comment]
Hi @huangli446688, the 100ms delay is for the first connection, to handle native wallets which are able to start very quickly. There's a backoff schedule, defined [here](https://github.com/solana-mobile/mobile-wallet-adapter/blob/main/android/clientlib/src/main/java/com/solana/mobilewalletadapter/clientlib/scenario/LocalAssociationScenario.java#L31), for retry attempts. This is an attempt to balance between very quick availability and the reality of wallet app startup times.

Can you share the 20ms connection timeout you are observing? There's a 200ms timeout defined [here](https://github.com/solana-mobile/mobile-wallet-adapter/blob/main/android/clientlib/src/main/java/com/solana/mobilewalletadapter/clientlib/scenario/LocalAssociationScenario.java#L32), but that is for the raw socket, which should be handled at the platform layer.

If you're observing timeouts, we'll definitely address these - flutter wallets and dapps are an important part of our developer base.

**Comment by huangli446688** [comment]
mConnectionBackoffExecutor.schedule(this::doTryConnect, CONNECT_BACKOFF_SCHEDULE_MS[0], TimeUnit.MILLISECONDS);
CONNECT_BACKOFF_SCHEDULE_MS[0] = 100，
It was only 100 milliseconds late to start the wallet application. 100 milliseconds can indeed complete socket connection and communication, but for applications, the callback of communication data has not been established. For the flutter wallet, 100mm has not entered the main function of the program, let alone establish the callback of communication data. I have tested some mobile phones. Because the time is too short, your demo can't work normally. It can only work normally on better mobile phones or simulators.

**Comment by sdlaver** [comment]
Hi @huangli446688, would you mind measuring the startup performance of your wallet app on low-tier hardware? We can expand the backoff schedule beyond it's current 3.1s to accommodate real-world performance on low-tier devices.

**Comment by huangli446688** [comment]
In our flutter wallet, DAPP configuration parameters are as follows, and it works well
    private static final int[] CONNECT_BACKOFF_SCHEDULE_MS = { 100, 250, 500, 1000 };
    private static final int CONNECT_TIMEOUT_MS = 800;
mConnectionBackoffExecutor.schedule(this::doTryConnect, CONNECT_BACKOFF_SCHEDULE_MS[3], TimeUnit.MILLISECONDS);

**Comment by sdlaver** [comment]
Thanks! I'll get the connection schedule updated today.
