### ISSUE TITLE
kotlin demo is not easy  for kotlin beginner to integrate 

### ISSUE THREAD

**Issue by AaronSmart** [solana-mobile/mobile-wallet-adapter#87]
the fakeapp and fakewallet is write in kotlin, i find it a little difficult to  translate  to android native java, I developed a  solana payment app，Is there any plan to promote this project to reduce the repeated wheel building . find more infomation: http://www.kikenn.com

**Comment by sdlaver** [comment]
We're currently working on libraries to map the `clientlib` implementation (which is implemented in Java) to all of the following frameworks:
- React Native
- RxJava
- Kotlin
Keep an eye out for these in the near future!

There are also some efforts underway for Dart+Flutter, but those aren't as far along.

**Comment by sdlaver** [comment]
Closing this issue; at this point, it isn't tracking any specific task, and has not had a comment in > 7 days
